### ISSUE TITLE
I Does Not Work.

### ISSUE THREAD

**Issue by vatsalcshah** [dena-csr/AppUsageWatcher#1] opened 2019-01-13 21:35 UTC
It isn't working I tried it on Android Pie.

**Comment by realnick** [comment] 2019-01-15 03:27
I will investigate.

**Comment by realnick** [comment] 2019-01-15 09:21
I see, checking app usage in the backround is limited since Android 8.0;
https://developer.android.com/about/versions/oreo/background

I should replace it with JobScheduler or startForegroundService.

**Comment by vatsalcshah** [comment] 2019-01-15 10:37
Yeah , I tested it on Android 9.0 , so maybe you have used some deprecated libraries. Anyways thanks for response.

**Comment by realnick** [comment] 2019-01-18 01:37
Hi vatsalcshah,

I fixed this issue on issues/1 branch and confirmed on my Android 8.0 device.
However, I don't have Android 9 device, so could you checkout issues/1 branch and try it again?
Once you launch the app, toggle the top right switch, and enable both user stat permission and overlay permission, and reload the list, then you could find the usages.

**Comment by realnick** [comment] 2019-02-10 01:18
Merged issues/1 to master.

**Closed as completed by realnick** 2019-02-10 01:18 UTC
